### ISSUE TITLE
Add Button to start the Game

### ISSUE THREAD

**Issue by NightHammer1000** [RoseTheFlower/UltrawideIndex#24]
This would be wonderful for us Steam Deck guys.

We can use the Steam Launch Arguments to launch a diffrent .exe in the Game Folder. That can be used to start the Fix. But starting the game afterwards is a bit tricky.

So, a Button to start the Game inside the fix would solve all our Problems.

**Comment by RoseTheFlower** [comment]
My solutions come in many forms. Sometimes it's a DLL injection or a patcher so that the game is fixed either permanently or until the next update, but I think you're referring to the trainers. A few of them can be run before the game, but the most reliable way is to require that they are run after the game.

There is a way to script a delayed launch of the trainer after the game (see the auto launcher [here](https://github.com/RoseTheFlower/UltrawideIndex/releases/tag/manhunt2), all the credits go to the original script author you'll see there).

It's certainly not impossible to code in a button that would launch a Steam app by its ID, but I try to make my solutions as universal as possible, so having that for those who play on Game Pass, Epic, Origin, GOG or what have you, is definitely not a viable idea.

**Comment by RoseTheFlower** [comment]
[You might find this useful though.](https://github.com/RoseTheFlower/UltrawideIndex/blob/main/instructions/dreamlightvalley.md)

I'll consider documenting it for other games if I end up making more fixes this way.
