### ISSUE TITLE
Outer Worlds: Spacer's Choice Edition Ultrawide patch not working.

### ISSUE THREAD

**Issue by DrR0Ck** [RoseTheFlower/UltrawideIndex#43]
I am running the game on Epic.  I've dropped the files into the Win64 folder, but am still seeing black bars during dialogs.  Haven't played so far into the game, but I think that's an indicator that things are not working properly.  There was a recent update for the Spacer's choice Edition, so it's possible that broke the patch.  Either that, or it's just not working on the Epic version of the game.  Any suggestions?  Thanks for your work!

**Comment by RoseTheFlower** [comment]
I do not have the game on Epic to test, but I checked with my GOG version after its latest update and then again today, and the fix is still working as intended on my end. Is the exe name Indiana-Win64-Shipping.exe on Epic? Also - not that I've had people explicitly run into this to indicate it's a requirement - do you have all the modern .NET frameworks installed?

![image](https://github.com/RoseTheFlower/UltrawideIndex/assets/4759227/55dace74-f89a-40f9-bfeb-31ee44820841)

**Comment by DrR0Ck** [comment]
Thanks for your response!  The exe on Epic is:  IndianaEpicGameStore-Win64-Shipping.exe.  Fairly certain I have all the .NET frameworks, but is there a specific one(s) I should verify?  My Win64 folder contents are below.  Aside from Windowed Fullscreen, is there any other in-game setting that would need to be applied?
![Win64 Folder](https://github.com/RoseTheFlower/UltrawideIndex/assets/47359983/92501e5b-f4a9-49e3-89f6-d14351f667b3)

**Comment by RoseTheFlower** [comment]
Try the new version with Epic support uploaded just now.

**Comment by DrR0Ck** [comment]
That did it!  Working properly now.  Thanks so much!
